const express = require("express");
const ejs = require("ejs");

const app = express();

app.set('view engine', 'ejs');

app.use(express.static("public"));

app.get("/",function(req,res){
dictionary = {
    "je demande" : ["pido"],
    "pardon" : ["perdón"],
    "aux" : ["a los","a las"],
    "enfants": ["niños"],
    "à" : ["para","a","en"],
    "d’avoir" : ["por haber"],
    "dédié" : ["dedicado"],
    "ce" : ["este"],
    "livre" : ["libro"],
    "une" : ["una"],
    "grande personne" : ["persona mayor"],
    "j’ai" : ["tengo"],
    "excuse" : ["excusa"],
    "sérieuse" : ["seria"],
    "cette" : ["esta"],
    "est" : ["es","esta"],
    "le" : ["el"],
    "meilleur" : ["mejor"],
    "ami" : ["amigo"],
    "que" : ["que"],
    "au" : ["en el","al","en"],
    "monde" : ["mundo"],
    "autre" : ["otra","otro"],
    "peut" : ["puede"],
    "tout comprendre" : ["comprenderlo todo"],
    "même" : ["incluso"],
    "les" : ["los","las"],
    "pour" : ["para"],
    "troisième" : ["tercera"],
    "habite la France" : ["vive en Francia"],
    "où" : ["donde"],
    "elle" : ["ella"],
    "a" : ["tiene"],
    "faim" : ["hambre"],
    "et" : ["y"],
    "froid" : ["frío"],
    "a bien besoin" : ["realmente necesita"],
    "d’être" : ["ser"],
    "consolée" : ["consolada"],
    "si" : ["si"],
    "toutes" : ["todas"],
    "ces" : ["estas"],
    "ne suffisent pas" : ["no son suficientes"],
    "je veux bien" : ["me gustaría"],
    "l’enfant" : ["el niño"],
    "qu’a été autrefois" : ["que era antes"],
    "ont d’abord été" : ["fueron primero"],
    "des enfants" : ["niños"],
    "mais" : ["pero"],
    "peu" : ["pocas","poco"],
    "d’entre" : ["de entre"],
    "elles" : ["ellas"],
    "s’en souviennent" : ["lo recuerdan"],
    "je corrige" : ["corrijo"],
    "donc" :["entonces"],
    "ma" : ["mi"],
    "dédicace" : ["dedicatoria"],
    "quand" : ["cuando"],
    "il" : ["el"],
    "livres" : ["libros"],
    "grandes personnes" : ["personas mayores"],
    "excuses" : ["excusas"],
    "dédier" : ["dedicar"],
    "était" : ["era","estaba"],
    "petit" : ["pequeño"],
    "garçon" : ["niño"],
    "ans" : ["años"],
    "un" : ["un"],
    "voilà" : ["aquí esta"],
    "six" : ["seis"],
    "image" : ["imagen"],
    "histoires" : ["historias"],
    "s’appelait" : ["se llamaba"],
    "sur" : ["sobre","con","en"],
    "du" : ["del","de","al"],
    "ça représentait" : ["representaba"],
    "vécues" : ["vividas"],
    "magnifique" : ["magnífica"],
    "j’ai vu" : ["vi"],
    "qui" : ["que","quien"],
    "copie" : ["copia"],
    "dans" : ["en","dentro"],
    "fauve" : ["fiera"],
    "serpent" : ["serpiente"],
    "forêt" : ["bosque"],
    "vierge" : ["virgen"],
    "j’avais" : ["tenía", "había"],
    "lorsque" : ["cuando"],
    "dessin" : ["dibujo"],
    "avalait" : ["tragaba"],
    "ça" : ["eso"],
    "boa" : ["boa"],
    "fois" : ["vez"],
    "la" : ["la"],
    "ensuite" : ["luego"],
    "tout" : ["todos"],
    "ils" : ["ellos"],
    "digestion" : ["digestión"],
    "pendant" : ["durante"],
    "mois" : ["meses","mes"],
    "proie" : ["presa"],
    "avalent" : ["tragan"],
    "sans" : ["sin"],
    "tout entière" : ["entera"],
    "plus" : ["más"],
    "de" : ["de"],
    "la mâcher" : ["masticarla"],
    "leur" : ["su"],
    "dorment" : ["duermen"],
    "on disait" : ["decía"],
    "boas" : ["boas"],
    "bouger" : ["mover"],
    "serpents" : ["serpientes"],
    "ne peuvent plus bouger" : ["no pueden moverse más"],
    "aventures" : ["aventuras"],
    "mon" : ["mi"],
    "avec" : ["con"],
    "alors" : ["entonces"],
    "numéro" : ["número"],
    "couleur" : ["color"],
    "crayon" : ["lápiz"],
    "jungle" : ["jungla"],
    "premier" : ["primer"],
    "comme ça" : ["así"],
    "beaucoup" : ["mucho"],
    "à tracer" : ["dibujar"],
    "j’ai alors beaucoup réfléchi" : ["entonces reflexioné mucho"],
    "à mon tour" : ["por mi parte"],
    "j’ai réussi" : ["logré"],
    "j’ai montré" : ["enseñé"],
    "peur" : ["miedo"],
    "chef-d’œuvre" : ["obra maestra"],
    "je leur ai demandé" : ["les pregunté"],
    "leur faisait peur" : ["los asustó"],
    "ferait-il peur" : ["daría miedo"],
    "chapeau" : ["sombrero"],
    "m’ont répondu" : ["me respondieron"],
    "pourquoi" : ["por qué"],
    "afin" : ["para"],
    "l’intérieur" : ["el interior"],
    "puissent" : ["pudieran"],
    "ont toujours besoin" : ["siempre necesitan"],
    "éléphant" : ["elefante"],
    "digérait" : ["digería"],
    "comprendre" : ["comprender"],
    "dessiné" : ["dibujé","dibujado"],
    "ne représentait pas" : ["no representaba"],
    "représentait" : ["representaba"],
    "d’explications" : ["de explicaciones"],
    "j’ai alors" : ["entonces"],
    "dessins" : ["dibujos"],
    "c’est" : ["es"],
    "carrière" : ["carrera"],
    "j’avais été" : ["me había"],
    "calcul" : ["cálculo"],
    "conseillé" : ["aconsejaron"],
    "ouverts" : ["abiertos"],
    "l’insuccès" : ["el fracaso"],
    "m’intéresser" : ["interesarme"],
    "géographie" : ["geografía"],
    "rien" : ["nada"],
    "grammaire" : ["gramática"],
    "laisser" : ["dejar"],
    "ou" : ["o"],
    "ainsi" : ["así"],
    "fatigant" : ["cansado"],
    "peintre" : ["pintor"],
    "toutes seules" : ["por sí mismas"],
    "leur donner des explications" : ["darles explicaciones"],
    "m’ont" : ["me"],
    "fermés" : ["cerrados"],
    "par" : ["por"],
    "l’histoire" : ["la historia"],
    "l’âge" : ["la edad"],
    "côté" : ["lado"],
    "plutôt" : ["en vez"],
    "toujours" : ["siempre"],
    "j’ai abandonné" : ["abandoné"],
    "découragé" : ["desanimado"],
    "ne comprennent jamais" : ["nunca comprenden"],
    "piloter" : ["volar"],
    "métier" : ["oficio"],
    "égaré" : ["perdido"],
    "j’ai volé" : ["volé"],
    "reconnaître" : ["reconocer"],
    "l’on" : ["uno"],
    "très" : ["muy"],
    "utile" : ["útil"],
    "je" : ["yo"],
    "chine" : ["China"],
    "c’est exact" : ["es correcto"],
    "savais" : ["sabía"],
    "partout" : ["por todo"],
    "des avions" : ["aviones"],
    "dû" : ["tuve que"],
    "l’arizona" : ["la Arizona"],
    "nuit" : ["noche"],
    "j’ai donc" : ["entonces"],
    "j’ai appris" : ["aprendí"],
    "choisir" : ["escoger"],
    "m’a beaucoup servi" : ["me ha servido mucho"],
    "coup d’œil" : ["vistazo"],
    "des tas" : ["muchos"],
    "eu" : ["tuve"],
    "de contacts" : ["contactos"],
    "vie" : ["vida"],
    "cours" : ["curso"],
    "de gens" : ["gente"],
    "sérieux" : ["seria"],
    "opinion" : ["opinión"],
    "près" : ["cerca"],
    "ai" : ["he"],
    "vues" : ["visto"],
    "j’ai ainsi" : ["así","entonces"],
    "j’ai beaucoup vécu" : ["He vivido mucho"],
    "chez" : ["entre"],
    "n’a pas trop amélioré" : ["no mejoró demasiado"],
    "me" : ["me"],
    "parlais" : ["hablaba"],
    "mettais" : ["ponía"],
    "vraiment" : ["realmente"],
    "savoir" : ["saber"],
    "vierges" : ["vírgenes"],
    "l’expérience" : ["la experiencia"],
    "bien" : ["muy","bien"],
    "d’étoiles" : ["de estrellas"],
    "conservé" : ["conservé"],
    "j’en rencontrais" : ["conocía"],
    "ni" : ["ni"],
    "sa" : ["su"],
    "homme" : ["hombre"],
    "cravates" : ["corbatas"],
    "répondait" : ["respondía"],
    "lui" : ["le","el"],
    "golf" : ["golf"],
    "voulais" : ["quería"],
    "forêts" : ["bosques"],
    "raisonnable" : ["razonable"],
    "connaître" : ["conocer"],
    "portée" : ["nivel"],
    "bridge" : ["bridge"],
    "faisais" : ["hacía"],
    "politique" : ["política"],
    "paraissait" : ["parecía"],
    "lucide" : ["lúcida"],
    "compréhensive" : ["comprensiva"],
    "aussi" : ["tan"],
    "ne" : ["no"],
    "personne" : ["nadie"],
    "j’ai toujours" : ["siempre"],
    "quelque chose" : ["algo"],
    "avec moi" : ["conmigo"],
    "moi":["mi"],
    "tout seul" : ["completamente solo"],
    "il y a" : ["hace"],
    "peine" : ["penas"],
    "réparation" : ["reparación"],
    "c’était" : ["era"],
    "seul" : ["solo"],
    "s’était" : ["se"],
    "comme" : ["como"],
    "mort" : ["muerte","muerto"],
    "cassé" : ["rompió"],
    "jours" : ["días"],
    "moteur" : ["motor"],
    "panne" : ["avería"],
    "question" : ["cuestión"],
    "véritablement" : ["verdaderamente"],
    "préparai" : ["preparé"],
    "l’eau" : ["la agua"],
    "jusqu’à" : ["hasta"],
    "difficile" : ["difícil"],
    "essayer" : ["tratar"],
    "n’avais" : ["no tenía","no había"],
    "boire" : ["beber"],
    "vécu" : ["viví"],
    "sahara" : ["Sahara"],
    "réussir" : ["lograr"],
    "désert" : ["desierto"],
    "passagers" : ["pasajeros"],
    "huit" : ["ocho"],
    "parler" : ["hablar"],
    "mécanicien" : ["mecánico"],
    "contente" : ["contenta"],
    "lever du jour" : ["amanecer"],
    "drôle de" : ["extraña"],
    "imaginez" : ["imagina"],
    "terre" : ["región"],
    "sable" : ["arena"],
    "mille" : ["mil"],
    "qu’un" : ["que un"],
    "petite" : ["pequeña"],
    "toute" : ["toda"],
    "réveillé" : ["despertó"],
    "milles" : ["millas"],
    "l’océan" : ["el oceano"],
    "m’a" : ["me"],
    "soir" : ["noche"],
    "habitée" : ["habitada"],
    "naufragé" : ["naufrago"],
    "milieu" : ["medio"],
    "vous" : ["usted"],
    "disait" : ["dijo"],
    "j’étais" : ["estaba","yo era"],
    "voix" : ["voz"],
    "isolé" : ["aislado"],
    "radeau" : ["balsa"],
    "surprise" : ["sorpresa"],
    "je me suis donc endormi" : ["entonces me quedé dormido"],
    "bien plus" : ["mucho más"],
    "s’il vous plaît" : ["por favor"],
    "dessine-moi" : ["dibujame"],
    "mouton" : ["oveja"],
    "hein" : ["eh"],
    "gravement" : ["seriamente"],
    "foudre" : ["rayo"],
    "mes" : ["mis"],
    "frappé" : ["golpeado"],
    "yeux" : ["ojos"],
    "considérait" : ["miraba"],
    "pieds" : ["pies"],
    "j’ai sauté" : ["salté"],
    "j’ai vu" : ["vi"],
    "petit bonhomme" : ["hombrecito"],
    "j’avais été" : ["me hubiera","me había"],
    "j’ai bien frotté" : ["me froté bien"],
    "j’ai bien regardé" : ["heche un buen vistazo"],
    "tout à fait extraordinaire" : ["bastante extraordinario"],
    "plus tard" : ["más tarde"],
    "à faire" : ["hacer"],
    "portrait" : ["retrato"],
    "j’ai réussi" : ["logré"],
    "bien sûr" : ["por supuesto"],
    "moins" : ["menos"],
    "appris" : ["aprendido"],
    "sauf" : ["salvo"],
    "dessiner" : ["dibujar"],
    "sûr" : ["sobre"],
    "ravissant" : ["encantador"],
    "personnes" : ["personas"],
    "ce n’est pas" : ["no es"],
    "faute" : ["culpa","falto"],
    "grandes" : ["grandes"],
    "modèle" : ["modelo"],
    "regardai" : ["miré"],
    "d’étonnement" : ["de asombro"],
    "ronds" : ["redondos"],
    "semblait" : ["parecía"],
    "fatigue" : ["fatiga"],
    "région" : ["región"],
    "en" : ["en"],
    "des" : ["unos","de los"],
    "or" : ["pero"],
    "perdu" : ["perdido"],
    "l’apparence" : ["la apariencia"],
    "trouvais" : ["encontraba"],
    "d’un" : ["de un"],
    "réussis" : ["logré"],
    "soif" : ["sed"],
    "dis" : ["dije"],
    "n’oubliez pas" : ["no olvides"],
    "n’avait" : ["no tenía"],
    "enfant" : ["niño"],
    "enfin" : ["finalmente"],
    "apparition" : ["aparición"],
    "tu" : ["tu"],
    "fais" : ["haces"],
    "qu’est-ce que" : ["que"],
    "là" : ["aquí"],
    "tout doucement" : ["muy suavemente"],
    "chose" : ["cosa"],
    "répéta" : ["repitió"],
    "endroits" : ["lugares"],
    "surtout" : ["sobretodo"],
    "trop" : ["demasiado"],
    "mauvaise" : ["mal"],
    "absurde" : ["absurdo"],
    "tous" : ["todos"],
    "mystère" : ["misterio"],
    "étudié" : ["estudiado"],
    "répondit" : ["respondió"],
    "habités" : ["habitados"],
    "papier" : ["papel"],
    "sortis" : ["saqué"],
    "rappelai" : ["acordé"],
    "impressionnant" : ["impresionante"],
    "stylographe" : ["estilógrafo"],
    "feuille" : ["hoja"],
    "danger" : ["peligro"],
    "poche" : ["bolsillo"],
    "humeur" : ["humor"],
    "on n’ose pas désobéir" : ["no nos atrevemos a desobedecer"],
    "que cela me semblâit" : ["como me pareció"],
    "ne savais pas" : ["no sabía"],
    "ça ne fait rien" : ["eso no importa"],
    "fermé" : ["cerrado"],
    "celui" : ["el"],
    "capable" : ["capaz"],
    "refis" : ["rehice"],
    "dont" : ["de los cuales"],
    "deux" : ["dos"],
    "seuls" : ["únicos"],
    "d’entendre" : ["escuchar"],
    "l’un" : ["uno"],
    "jamais" : ["nunca"],
    "je fus stupéfait" : ["yo estaba impresionado"],
    "me répondre" : ["responderme"],
    "non" : ["no"],
    "ne veux pas" : ["no quiero"],
    "dangereux" : ["peligroso"],
    "encombrant" : ["voluminoso"],
    "chez moi" : ["en mi casa"],
    "c’est tout petit" : ["todo es muy pequeño"],
    "j’ai besoin" : ["necesito"],
    "j’ai dessiné" : ["dibujé"],
    "attentivement" : ["atentamente"],
    "regarda" : ["miró"],
    "puis" : ["después"],
    "celui-là" : ["ese"],
    "est déjà" : ["ya esta"],
    "fais-en un autre" : ["haz otro"],
    "malade" : ["enfermo"],
    "dessinai" : ["dibujé"],
    "gentiment" : ["amablemente"],
    "sourit" : ["sonrió"],
    "indulgence" : ["indulgencia"],
    "bélier" : ["carnero"],
    "des cornes" : ["cuernos"],
    "tu vois" : ["mira"],
    "n’est pas" : ["no es"],
    "encore" : ["nuevamente"],
    "refusé" : ["rechazado"],
    "fut" : ["fué"],
    "précédents" : ["anteriores"],
    "longtemps" : ["mucho tiempo"],
    "veux" : ["quiero","quieres"],
    "vive" : ["viva"],
    "vieux" : ["viejo"],
    "démontage" : ["desmontaje"],
    "hâte" : ["prisa"],
    "dessin-ci" : ["dibujo"],
    "patience" : ["paciencia"],
    "commencer" : ["comenzar"],
    "griffonnai" : ["garabateé"],
    "lançai" : ["lancé"],
    "caisse" : ["caja"],
    "dedans" : ["adentro"],
    "voir" : ["ver"],
    "visage" : ["cara"],
    "je fus bien surpris" : ["me sorprendió"],
    "juge" : ["juez"],
    "jeune" : ["joven"],
    "s’illuminer" : ["iluminarse"],
    "crois-tu" : ["Tu crees"],
    "d’herbe" : ["hierba"],
    "qu’il faille beaucoup" : ["que se necesite mucha"],
    "tout à fait" : ["totalmente"],
    "ça que je le voulais" : ["lo que yo quería"],
    "parce que" : ["porque"],
    "sûrement" : ["seguramente"],
    "t’ai donné" : ["te di"],
    "suffira" : ["será suficiente"],
    "tout petit" : ["muy pequeño"],
    "vers" : ["hacia"],
    "tête" : ["cabeza"],
    "pencha" : ["inclinó"],
    "tiens" : ["aquí"],
    "endormi" : ["dormido"],
    "s’est" : ["se ha"],
    "petit prince" : ["principito"],
    "pas si petit que ça" :["no tan pequeño"],
    "je fis la connaissance" : ["llegue a conocer"]
  }

  res.render("index",dictionary);
});

app.listen(8080, function() {
  console.log("Server started on port 8080");
});
